GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Word Aligned",
    "author": "Thomas Guest",
    "url": "http://wordaligned.org",
    "likes": 999
}
