###
# @name login
POST http://localhost:3001/api/login
content-type: application/json

{
    "name": "Thomas Guest",
    "username": "thomas",
    "password": "1234"
}
###
GET http://localhost:3001/api/blogs

###
# @name create
POST http://localhost:3001/api/blogs
content-type: application/json
authorization: bearer {{login.response.body.token}}

{
    "title": "Word Aligned",
    "author": "Thomas Guest",
    "url": "http://wordaligned.org"
}

###
DELETE http://localhost:3001/api/blogs/{{create.response.body.id}}
authorization: bearer {{login.response.body.token}}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Thomas Guest",
    "username": "thomas",
    "password": "1234"
}
