GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/5eadbc85a01ddc131888abe9

###
GET http://localhost:3001/api/persons/666

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/24056

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Daniel",
    "number": "123-456"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Thomas"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "123-456"
}
